
install-package:       # This job runs in the build stage, which runs first.
  image: python:latest
  stage: build
  script:
    - echo "Hello world"
    - pip install --upgrade pip
    - pip config set global.index-url "https://gitlab.dlr.de/api/v4/projects/30090/packages/pypi/simple"
    - pip install at-packaging-tools
    - create_changed_packages --help


